DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE CUENTAS CASCADE CONSTRAINTS;
DROP TABLE MOVIMIENTOS CASCADE CONSTRAINTS;
DROP TABLE OFICINAS CASCADE CONSTRAINTS;
DROP TABLE TITULARES CASCADE CONSTRAINTS;