CREATE ROLE TILIN_SUPREMO;
GRANT ALL ON CUENTAS TO TILIN_SUPREMO;
GRANT ALL ON CLIENTES TO TILIN_SUPREMO;
GRANT ALL ON MOVIMIENTOS TO TILIN_SUPREMO;
GRANT ALL ON OFICINAS TO TILIN_SUPREMO;
GRANT ALL ON TITULARES TO TILIN_SUPREMO;

GRANT TILIN_SUPREMO TO is331516;
GRANT TILIN_SUPREMO TO is331511;