DROP TABLE cliente CASCADE CONSTRAINTS;

CREATE TABLE cliente(
    nombre VARCHAR2(50),
    genero VARCHAR2(10),
    edad INTEGER,
    id_cliente NUMBER(5, 0) GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT pk_id PRIMARY KEY(id_cliente),
    CONSTRAINT chk_genero CHECK (genero IN ('femenino', 'masculino'))
);

INSERT INTO cliente(nombre, genero, edad)
VALUES ('Juan', 'masculino', 18);

COMMIT;