DROP TABLE BOOKS CASCADE CONSTRAINTS;
CREATE TABLE BOOKS 
   (	
   BOOK_ID VARCHAR2(20 BYTE) PRIMARY KEY, 
	TITLE VARCHAR2(50 BYTE), 
	AUTHOR_LAST_NAME VARCHAR2(30 BYTE), 
	AUTHOR_FIRST_NAME VARCHAR2(30 BYTE), 
	RATING NUMBER
   );

commit;

Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A1111','MOBY DICK2','Melville','Herman','5,5');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A2222','GET RICH REALLY FAST','Scammer','Ima','8');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A3333','Finding Inner Peace','Blissford','Serenity','3');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A4444','Great Mystery Stories','Whodunit','Rodney','3');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A5555','Software Wizardry','Abugov',null,'7');

commit;   