DROP TABLE BOOKS CASCADE CONSTRAINTS;
CREATE TABLE BOOKS 
   (	
   BOOK_ID VARCHAR2(20 BYTE) PRIMARY KEY, 
	TITLE VARCHAR2(50 BYTE), 
	AUTHOR_LAST_NAME VARCHAR2(30 BYTE), 
	AUTHOR_FIRST_NAME VARCHAR2(30 BYTE), 
	RATING number
   );

commit;

Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A1111','MOBY DICK2','Melville','Herman','5.5');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A2222','GET RICH REALLY FAST','Scammer','Ima','8');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A3333','Finding Inner Peace','Blissford','Serenity','3');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A4444','Great Mystery Stories','Whodunit','Rodney','3');
Insert into BOOKS (BOOK_ID,TITLE,AUTHOR_LAST_NAME,AUTHOR_FIRST_NAME,RATING) values ('A5555','Software Wizardry','Abugov',null,'7');

commit;   

DROP TABLE TRACK_AUDITOR CASCADE CONSTRAINTS;
CREATE TABLE TRACK_AUDITOR
(
    ID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,
    USUARIO VARCHAR2(50 BYTE),
    VALOR_ANTERIOR VARCHAR2(100 BYTE),
    VALOR_NUEVO VARCHAR2(100 BYTE),
    OPERACION VARCHAR2(100 BYTE),
    FECHA DATE DEFAULT sysdate,
    PRIMARY KEY(ID)
);



CREATE OR REPLACE TRIGGER TRG_INS_AUDITORIA BEFORE 
UPDATE OF AUTHOR_LAST_NAME ON BOOKS
FOR EACH ROW 
BEGIN 
    INSERT INTO TRACK_AUDITOR(
        USUARIO,
        VALOR_ANTERIOR,
        VALOR_NUEVO,
        OPERACION,
        FECHA
    ) VALUES(
        sys_context('userenv', 'current_user'),
        :old.AUTHOR_LAST_NAME,
        :new.AUTHOR_LAST_NAME,
        'UPDATE',
        SYSDATE
    );
END;
/

UPDATE BOOKS
SET AUTHOR_LAST_NAME = 'me papie a faby'
WHERE RATING = 8;

COMMIT;

SELECT * FROM TRACK_AUDITOR;
