CREATE TABLE "PERSONA" (
  "ID_PERSONA" NUMERIC(10,0) PRIMARY KEY,
  "NOMBRE" VARCHAR2(70) NOT NULL,
  "APELLIDO" VARCHAR2(70) NOT NULL,
  "CORREO" VARCHAR2(70) NOT NULL,
  "TELEFONO" NUMERIC(10,0)
);

CREATE TABLE "EXPOSITOR" (
  "ID_PERSONA" NUMERIC(10,0) PRIMARY KEY
);

CREATE TABLE "ESTUDIANTE" (
  "ID_PERSONA" NUMERIC(10,0) PRIMARY KEY,
  "ID_DIPLOMADO" NUMERIC(10,0) NOT NULL
);

CREATE TABLE "DIPLOMADO" (
  "ID_DIPLOMADO" NUMERIC(10,0) PRIMARY KEY,
  "COSTO" NUMERIC(12,2) NOT NULL,
  "NOMBRE" VARCHAR2(50) NOT NULL,
  "ID_PERSONA" NUMERIC(10,0) NOT NULL
);

CREATE TABLE "TRANSACCION" (
  "ID_TRANSACCION" NUMERIC(10,0) PRIMARY KEY,
  "FECHA" DATE NOT NULL,
  "ID_PERSONA" NUMERIC(10,0) NOT NULL,
  "ID_DIPLOMADO" NUMERIC(10,0) NOT NULL
);

CREATE TABLE "TARJETA" (
  "ID_TARJETA" NUMERIC(16,0) PRIMARY KEY,
  "CVC_TARJETA" NUMERIC(3,0) NOT NULL,
  "EXPIRACION" DATE NOT NULL
);

CREATE TABLE "TRANSACCIONXTARJETA" (
  "ID_TARJETA" NUMERIC(10,0),
  "ID_TRANSACCION" NUMERIC(10,0),
  PRIMARY KEY ("ID_TARJETA", "ID_TRANSACCION")
);

CREATE TABLE "IDIOMA" (
  "ID_IDIOMA" NUMERIC(5,0) PRIMARY KEY,
  "NOMBRE" VARCHAR2(50)
);

CREATE TABLE "NIVEL" (
  "ID_NIVEL" NUMERIC(2,0) PRIMARY KEY,
  "NIVEL" INTEGER,
  "P_ESCRITURA" NUMERIC(0,3),
  "P_LECTURA" NUMERIC(0,3),
  "P_HABLA" NUMERIC(0,3)
);

CREATE TABLE "IDIOMAXNIVEL" (
  "ID_IDIOMA" NUMERIC(5,0),
  "ID_NIVEL" NUMERIC(2,0),
  "ID_PERSONA" NUMERIC(10,0),
  PRIMARY KEY ("ID_IDIOMA", "ID_NIVEL", "ID_PERSONA")
);

CREATE TABLE "UNIVERSIDADXCARRERA" (
  "ID_PERSONA" NUMERIC(10,0),
  "ID_CARRERA" NUMERIC(10,0),
  "ID_UNIVERSIDAD" NUMERIC(5,0),
  PRIMARY KEY ("ID_PERSONA", "ID_CARRERA", "ID_UNIVERSIDAD")
);

CREATE TABLE "UNIVERSIDAD" (
  "ID_UNIVERSIDAD" NUMERIC(5,0) PRIMARY KEY,
  "NOMBRE" VARCHAR2(100),
  "DIRECCION" VARCHAR2(70)
);

CREATE TABLE "CARRERA" (
  "ID_CARREREA" NUMERIC(10,0) PRIMARY KEY,
  "NOMBRE" VARCHAR2(70),
  "CREDITOS" INTEGER
);

ALTER TABLE "PERSONA" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "EXPOSITOR" ("ID_PERSONA");

ALTER TABLE "PERSONA" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "ESTUDIANTE" ("ID_PERSONA");

ALTER TABLE "DIPLOMADO" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "EXPOSITOR" ("ID_PERSONA");

ALTER TABLE "ESTUDIANTE" ADD FOREIGN KEY ("ID_DIPLOMADO") REFERENCES "DIPLOMADO" ("ID_DIPLOMADO");

ALTER TABLE "TRANSACCION" ADD FOREIGN KEY ("ID_DIPLOMADO") REFERENCES "DIPLOMADO" ("ID_DIPLOMADO");

ALTER TABLE "TRANSACCION" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "ESTUDIANTE" ("ID_PERSONA");

ALTER TABLE "TRANSACCIONXTARJETA" ADD FOREIGN KEY ("ID_TRANSACCION") REFERENCES "TRANSACCION" ("ID_TRANSACCION");

ALTER TABLE "TRANSACCIONXTARJETA" ADD FOREIGN KEY ("ID_TARJETA") REFERENCES "TARJETA" ("ID_TARJETA");

ALTER TABLE "IDIOMAXNIVEL" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA");

ALTER TABLE "IDIOMAXNIVEL" ADD FOREIGN KEY ("ID_IDIOMA") REFERENCES "IDIOMA" ("ID_IDIOMA");

ALTER TABLE "IDIOMAXNIVEL" ADD FOREIGN KEY ("ID_NIVEL") REFERENCES "NIVEL" ("ID_NIVEL");

ALTER TABLE "UNIVERSIDADXCARRERA" ADD FOREIGN KEY ("ID_CARRERA") REFERENCES "CARRERA" ("ID_CARREREA");

ALTER TABLE "UNIVERSIDADXCARRERA" ADD FOREIGN KEY ("ID_UNIVERSIDAD") REFERENCES "UNIVERSIDAD" ("ID_UNIVERSIDAD");

ALTER TABLE "UNIVERSIDADXCARRERA" ADD FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA" ("ID_PERSONA");
