CREATE TABLE PERSONA (
  ID_PERSONA NUMERIC(10,0) PRIMARY KEY,
  NOMBRE VARCHAR2(70)  NOT NULL,
  APELLIDO VARCHAR2(70)  NOT NULL,
  CORREO VARCHAR2(70)  NOT NULL,
  TELEFONO NUMERIC(10,0)
);

CREATE TABLE UNIVERSIDAD (
  ID_UNIVERSIDAD NUMERIC(5,0)  PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  DIRECCION VARCHAR2(70)
);

CREATE TABLE CARRERA (
  ID_CARRERA NUMERIC(10,0) PRIMARY KEY,
  NOMBRE VARCHAR2(70) NOT NULL,
  CREDITOS INTEGER
);

CREATE TABLE IDIOMA (
  ID_IDIOMA NUMERIC(5,0) PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE NIVEL (
  ID_NIVEL NUMERIC(2,0) PRIMARY KEY,
  NIVEL INTEGER,
  P_ESCRITURA NUMBER(5,3),
  P_LECTURA NUMBER(5,3),
  P_HABLA NUMBER(5,3)
);

CREATE TABLE TARJETA (
  ID_TARJETA  NUMERIC(16,0) PRIMARY KEY,
  CVC_TARJETA NUMERIC(3,0) NOT NULL,
  EXPIRACION  DATE NOT NULL
);

CREATE TABLE EXPOSITOR (
  ID_PERSONA NUMERIC(10,0) PRIMARY KEY,
  CONSTRAINT fk_expositor_persona
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE DIPLOMADO (
  ID_DIPLOMADO NUMERIC(10,0)  PRIMARY KEY,
  COSTO NUMERIC(12,2) NOT NULL,
  NOMBRE VARCHAR2(50) NOT NULL,
  ID_PERSONA NUMERIC(10,0) NOT NULL,
  CONSTRAINT fk_diplomado_expositor
    FOREIGN KEY (ID_PERSONA) REFERENCES EXPOSITOR (ID_PERSONA)
);

CREATE TABLE ESTUDIANTE (
  ID_PERSONA   NUMERIC(10,0) PRIMARY KEY,
  ID_DIPLOMADO NUMERIC(10,0) NOT NULL,
  CONSTRAINT fk_estudiante_persona
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA   (ID_PERSONA),
  CONSTRAINT fk_estudiante_diplomado
    FOREIGN KEY (ID_DIPLOMADO) REFERENCES DIPLOMADO (ID_DIPLOMADO)
);

CREATE TABLE TRANSACCION (
  ID_TRANSACCION NUMERIC(10,0) PRIMARY KEY,
  FECHA DATE NOT NULL,
  ID_PERSONA NUMERIC(10,0) NOT NULL,
  ID_DIPLOMADO NUMERIC(10,0) NOT NULL,
  CONSTRAINT fk_transaccion_estudiante
    FOREIGN KEY (ID_PERSONA) REFERENCES ESTUDIANTE (ID_PERSONA),
  CONSTRAINT fk_transaccion_diplomado
    FOREIGN KEY (ID_DIPLOMADO) REFERENCES DIPLOMADO  (ID_DIPLOMADO)
);

CREATE TABLE TRANSACCIONXTARJETA (
  ID_TARJETA NUMERIC(16,0),
  ID_TRANSACCION NUMERIC(10,0),
  PRIMARY KEY (ID_TARJETA, ID_TRANSACCION),
  CONSTRAINT fk_txt_tarjeta
    FOREIGN KEY (ID_TARJETA) REFERENCES TARJETA (ID_TARJETA),
  CONSTRAINT fk_txt_transaccion
    FOREIGN KEY (ID_TRANSACCION) REFERENCES TRANSACCION (ID_TRANSACCION)
);

CREATE TABLE IDIOMAXNIVEL (
  ID_IDIOMA NUMERIC(5,0),
  ID_NIVEL NUMERIC(2,0),
  ID_PERSONA NUMERIC(10,0),
  PRIMARY KEY (ID_IDIOMA, ID_NIVEL, ID_PERSONA),
  CONSTRAINT fk_ixn_idioma
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA (ID_IDIOMA),
  CONSTRAINT fk_ixn_nivel
    FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL (ID_NIVEL),
  CONSTRAINT fk_ixn_persona
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE UNIVERSIDADXCARRERA (
  ID_PERSONA NUMERIC(10,0),
  ID_CARRERA NUMERIC(10,0),
  ID_UNIVERSIDAD NUMERIC(5,0),
  PRIMARY KEY (ID_PERSONA, ID_CARRERA, ID_UNIVERSIDAD),
  CONSTRAINT fk_uxc_persona
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
  CONSTRAINT fk_uxc_carrera
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERA (ID_CARRERA),
  CONSTRAINT fk_uxc_universidad
    FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (ID_UNIVERSIDAD)
);