--query 3
SELECT u.NOMBRE "UNIVERSIDAD", c.NOMBRE "CARRERA", count(*) "CANTIDAD"
FROM ESTUDIANTE e
JOIN DIPLOMADO d ON e.ID_DIPLOMADO = d.ID_DIPLOMADO
JOIN UNIVERSIDADXCARRERA uc ON e.ID_PERSONA = uc.ID_PERSONA
JOIN UNIVERSIDAD u ON u.ID_UNIVERSIDAD = uc.ID_UNIVERSIDAD
JOIN CARRERA c ON c.ID_CARRERA = uc.ID_CARRERA
WHERE d.NOMBRE = 'BLOCKCHAIN'
GROUP BY u.NOMBRE, c.NOMBRE;

--query 5
SELECT p.ID_PERSONA "DOCUMENTO", p.NOMBRE "NOMBRE", p.APELLIDO "APELLIDOS" --nos falta el tipo de documento juasjuas
FROM PERSONA p
WHERE p.ID_PERSONA IN(
    SELECT ID_PERSONA
    FROM ESTUDIANTE)
AND
p.ID_PERSONA IN(
    SELECT ID_PERSONA
    FROM EXPOSITOR
);