--query 1
SELECT 
    p.TIPODOC || ' ' || p.DOCUMENTO "DOCUMENTO", 
    p.NOMBRE || ' ' || p.APELLIDO "NOMBRES Y APELLIDOS"

FROM PERSONA P
    INNER JOIN EXPOSITOR e ON p.ID_PERSONA = e.ID_PERSONA
    INNER JOIN DIPLOMADO d ON e.ID_PERSONA = d.ID_PERSONA
WHERE d.NOMBRE = 'BLOCKCHAIN';

--query 2
SELECT 
    P.TIPODOC || ' ' || P.DOCUMENTO "DOCUMENTO",
    P.NOMBRE || ' ' || P.APELLIDO "NOMBRES Y APELLIDOS"

FROM PERSONA P
    INNER JOIN ESTUDIANTE E ON E.ID_PERSONA = P.ID_PERSONA
    INNER JOIN DIPLOMADO D ON D.ID_DIPLOMADO = E.ID_DIPLOMADO
WHERE D.NOMBRE = 'BLOCKCHAIN';

--query 3
SELECT 
    u.NOMBRE "UNIVERSIDAD", 
    c.NOMBRE "CARRERA", 
    count(*) "CANTIDAD"
FROM ESTUDIANTE e
    INNER JOIN DIPLOMADO d ON e.ID_DIPLOMADO = d.ID_DIPLOMADO
    INNER JOIN UNIVERSIDADXCARRERA uc ON e.ID_PERSONA = uc.ID_PERSONA
    INNER JOIN UNIVERSIDAD u ON u.ID_UNIVERSIDAD = uc.ID_UNIVERSIDAD
    INNER JOIN CARRERA c ON c.ID_CARRERA = uc.ID_CARRERA
WHERE d.NOMBRE = 'BLOCKCHAIN'
GROUP BY u.NOMBRE, c.NOMBRE;

--query 4
WITH EstudiantesIngles AS 
(
    SELECT 
        P.TIPODOC, 
        P.DOCUMENTO, 
        P.NOMBRE, 
        P.APELLIDO, 
        N.P_ESCRITURA
    FROM PERSONA P
    INNER JOIN ESTUDIANTE E ON E.ID_PERSONA = P.ID_PERSONA
    INNER JOIN IDIOMAXNIVEL X ON X.ID_PERSONA = P.ID_PERSONA
    INNER JOIN NIVEL N ON N.ID_NIVEL = X.ID_NIVEL
    INNER JOIN IDIOMA I ON I.ID_IDIOMA = X.ID_IDIOMA
    WHERE I.NOMBRE = 'Inglés'
)
SELECT 
    TIPODOC || ' ' || DOCUMENTO "DOCUMENTO",
    NOMBRE || ' ' || APELLIDO "NOMBRES Y APELLIDOS"
FROM EstudiantesIngles
WHERE P_ESCRITURA = 
    (
        SELECT MAX(P_ESCRITURA) 
        FROM EstudiantesIngles
    );

--query 5
SELECT 
    p.TIPODOC || ' ' || p.DOCUMENTO "DOCUMENTO", 
    p.NOMBRE "NOMBRE", 
    p.APELLIDO "APELLIDOS" 

FROM PERSONA p
WHERE 
p.ID_PERSONA IN
    (
        SELECT ID_PERSONA
        FROM ESTUDIANTE
    )
AND p.ID_PERSONA IN
    (
        SELECT ID_PERSONA
        FROM EXPOSITOR
    );
