CREATE TABLE PAIS
(
    NOMBRE_PAIS     VARCHAR2(70), --Aquí hay que meter un constraint
    ID              NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY     (ID)
);

CREATE TABLE CIUDAD
(
    NOMBRE_CIUDAD   VARCHAR2(70), --Aquí hay que meter otro constraint
    ID_PAIS         NUMBER(10, 0), --Va una FK
    ID              NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY     (ID)
);

CREATE TABLE ESTADIO
(
    NOMBRE_ESTADIO  VARCHAR2(70), --Aquí va un constraint también
    CAPACIDAD       INTEGER,
    ID_CIUDAD       NUMBER(10, 0), --Va una FK
    ID              NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (ID)
);

CREATE TABLE CONFEDERACION
(
    NOMBRE_CONFEDERACION VARCHAR2(70), --Oooootro constraint
    ID NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (ID)
);

CREATE TABLE SELECCION
(
    NOMBRE_SELECCION    VARCHAR2(70), --Aquí va un constraint
    ID_CONFEDERACION    NUMBER(10, 0), --Aquí va una FK
    ID                  NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (ID)
);

CREATE TABLE PARTIDO
(
    ID_ESTADIO              NUMBER(10, 0), --FK
    FECHA                   DATE,
    FASE                    VARCHAR2(10),
    ID_SELECCION_LOCAL      NUMBER(10, 0), --FK
    ID_SELECCION_VISITANTE  NUMBER(10, 0), --FK
    GOLES_LOCAL             INTEGER,
    GOLES_VISITANTE         INTEGER,
    ID              NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY     (ID)
);