--cambio de prueba

DROP TABLE CIUDAD           CASCADE CONSTRAINTS;
DROP TABLE CONFEDERACION    CASCADE CONSTRAINTS;
DROP TABLE ESTADIO          CASCADE CONSTRAINTS;
DROP TABLE PAIS             CASCADE CONSTRAINTS;
DROP TABLE PARTIDO          CASCADE CONSTRAINTS;
DROP TABLE SELECCION        CASCADE CONSTRAINTS;
DROP VIEW DATOS;