CREATE TABLE "PAIS" (
  "NOMBRE_PAIS" VARCHAR2(70) NOT NULL,
  "id_pais" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "IVA" NUMBER(0,4) NOT NULL
);

CREATE TABLE "CIUDAD" (
  "NOMBRE_CIUDAD" VARCHAR2(70) NOT NULL,
  "ID_PAIS" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "id_ciudad" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "impuesto_local" NUMBER(0,4) NOT NULL
);

CREATE TABLE "CONFEDERACION" (
  "NOMBRE_CONFEDERACION" VARCHAR2(70) NOT NULL,
  "id_confederacion" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY
);

CREATE TABLE "ESTADIO" (
  "NOMBRE_ESTADIO" VARCHAR2(70) NOT NULL,
  "CAPACIDAD" INTEGER DEFAULT 0 NOT NULL,
  "ID_CIUDAD" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "id_estadio" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY
);

CREATE TABLE "SELECCION" (
  "NOMBRE_SELECCION" VARCHAR2(70) NOT NULL,
  "ID_CONFEDERACION" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "id_seleccion" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY
);

CREATE TABLE "PARTIDO" (
  "ID_ESTADIO" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "FECHA" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "FASE" VARCHAR2(10) NOT NULL,
  "ID_SELECCION_LOCAL" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "ID_SELECCION_VISITANTE" NUMBER(10,0) DEFAULT 0 NOT NULL,
  "GOLES_LOCAL" INTEGER DEFAULT 0 NOT NULL,
  "GOLES_VISITANTE" INTEGER DEFAULT 0 NOT NULL,
  "id_partido" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "id_experiencia" NUMBER(10,0)
);

CREATE TABLE "Experiencia" (
  "id_experiencia" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "cupos_disponibles" integer,
  "descripcion" VARCHAR2(1000),
  "estado" VARCHAR2(15),
  "precio_base" NUMBER(12,4),
  "id_guia" NUMBER(10,0) NOT NULL,
  "precio_total" NUMBER(12,4) DEFAULT 0
);

CREATE TABLE "Guia" (
  "id_guia" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR2(20),
  "guia_jefe" NUMBER(10,0),
  "id_nivel" VARCHAR2(10)
);

CREATE TABLE "Nivel" (
  "id_nivel" VARCHAR2(10) PRIMARY KEY,
  "valorxhora" NUMBER(10,2)
);

CREATE TABLE "ServicioXExperiencia" (
  "id_servicio" NUMBER(10,0),
  "id_experiencia" NUMBER(10,0),
  "cantidad" integer,
  PRIMARY KEY ("id_servicio", "id_experiencia")
);

CREATE TABLE "Servicio" (
  "id_servicio" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR2(50),
  "descripcion" VARCHAR2(1000),
  "costo_adicional" NUMBER(12,4),
  "id_impuesto" NUMBER(10,0)
);

CREATE TABLE "Impuesto" (
  "id_impuesto" NUMBER(10,0) PRIMARY KEY,
  "valor" NUMBER(0,4),
  "tipo_impuesto" VARCHAR2(20)
);

CREATE TABLE "Cliente" (
  "nombre" VARCHAR2(30),
  "apellido" VARCHAR2(30),
  "tipo_documento" VARCHAR2(2),
  "id_cliente" NUMBER(10,0) GENERATED AS IDENTITY PRIMARY KEY,
  "numero_telefono" NUMBER(10,0),
  "email" VARCHAR2(50)
);

CREATE TABLE "ClienteXExperiencia" (
  "id_experiencia" NUMBER(10,0),
  "id_cliente" NUMBER(10,0),
  PRIMARY KEY ("id_experiencia", "id_cliente")
);

CREATE UNIQUE INDEX "UQ_NOMBRE_PAIS" ON "PAIS" ("NOMBRE_PAIS");

CREATE UNIQUE INDEX "UQ_NOMBRE_CIUDAD" ON "CIUDAD" ("NOMBRE_CIUDAD");

CREATE UNIQUE INDEX "UQ_NOMBRE_CONFEDERACION" ON "CONFEDERACION" ("NOMBRE_CONFEDERACION");

CREATE UNIQUE INDEX "UQ_NOMBRE_ESTADIO" ON "ESTADIO" ("NOMBRE_ESTADIO");

CREATE UNIQUE INDEX "UQ_NOMBRE_SELECCION" ON "SELECCION" ("NOMBRE_SELECCION");

COMMENT ON TABLE "CIUDAD" IS 'CHK_ID_PAIS: ID_PAIS >= 0
';

COMMENT ON TABLE "ESTADIO" IS 'CHK_CAPACIDAD: CAPACIDAD >= 0
CHK_ID_CIUDAD: ID_CIUDAD >= 0
';

COMMENT ON TABLE "SELECCION" IS 'CHK_ID_CONFEDERACION: ID_CONFEDERACION >= 0
';

COMMENT ON TABLE "PARTIDO" IS 'CHK_ID_ESTADIO: ID_ESTADIO >= 0
CHK_ID_SEL_LOCAL: ID_SELECCION_LOCAL >= 0
CHK_ID_SEL_VIS: ID_SELECCION_VISITANTE >= 0
CHK_GOLES_LOCAL: GOLES_LOCAL >= 0
CHK_GOLES_VIS: GOLES_VISITANTE >= 0
CHK_FASE: FASE IN (''GRUPOS'', ''OCTAVOS'', ''CUARTOS'', ''SEMIFINAL'', ''FINAL'')
CHK_JUGAR_SI_MISMA: ID_SELECCION_LOCAL != ID_SELECCION_VISITANTE
';

COMMENT ON TABLE "Experiencia" IS 'CHK_ESTADO: estado IN (''disponible'', ''agotada'', ''cancelada'')
';

ALTER TABLE "CIUDAD" ADD FOREIGN KEY ("ID_PAIS") REFERENCES "PAIS" ("id_pais") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ESTADIO" ADD FOREIGN KEY ("ID_CIUDAD") REFERENCES "CIUDAD" ("id_ciudad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SELECCION" ADD FOREIGN KEY ("ID_CONFEDERACION") REFERENCES "CONFEDERACION" ("id_confederacion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PARTIDO" ADD FOREIGN KEY ("ID_ESTADIO") REFERENCES "ESTADIO" ("id_estadio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PARTIDO" ADD FOREIGN KEY ("ID_SELECCION_LOCAL") REFERENCES "SELECCION" ("id_seleccion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PARTIDO" ADD FOREIGN KEY ("ID_SELECCION_VISITANTE") REFERENCES "SELECCION" ("id_seleccion") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PARTIDO" ADD FOREIGN KEY ("id_experiencia") REFERENCES "Experiencia" ("id_experiencia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Experiencia" ADD FOREIGN KEY ("id_guia") REFERENCES "Guia" ("id_guia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Guia" ADD FOREIGN KEY ("guia_jefe") REFERENCES "Guia" ("id_guia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Guia" ADD FOREIGN KEY ("id_nivel") REFERENCES "Nivel" ("id_nivel") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ServicioXExperiencia" ADD FOREIGN KEY ("id_servicio") REFERENCES "Servicio" ("id_servicio") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ServicioXExperiencia" ADD FOREIGN KEY ("id_experiencia") REFERENCES "Experiencia" ("id_experiencia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Servicio" ADD FOREIGN KEY ("id_impuesto") REFERENCES "Impuesto" ("id_impuesto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ClienteXExperiencia" ADD FOREIGN KEY ("id_experiencia") REFERENCES "Experiencia" ("id_experiencia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ClienteXExperiencia" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id_cliente") DEFERRABLE INITIALLY IMMEDIATE;
